
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_TOPIC_LIST = "UPDATE_TOPIC_LIST";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const UPDATE_HAS_MESSAGE = "UPDATE_HAS_MESSAGE";
export const SET_TIME_INTERVAL = "SET_TIME_INTERVAL";
export const CLEAR_TIME_INTERVAL = "CLEAR_TIME_INTERVAL";
export const UPDATE_MASTER_LIST = "UPDATE_MASTER_LIST";